name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          package-manager-cache: false

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Publish to NPM
        uses: changesets/action@v1
        id: changesets
        with:
          publish: pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_PUBLISHING_TOKEN }}

      - name: Publish to GitHub
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          cat << EOF > "$HOME/.npmrc"
          @YOUR_SCOPE:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
          EOF
        with:
          publish: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

